import { people } from "./content";
import { klein } from "./licht";
import { useLanguage } from "./i18n/context";
import LinkedInMark from "./LinkedInMark";
import "./advisory-partner.css";

const copy: Record<string, { title: string; intro: string; experience: string }> = {
  nl: { title: "Extern adviseur en klankbord", intro: "Vanuit die ervaring denkt Albert mee over de ontwikkeling, koers, groei en strategische keuzes van SocialNow.", experience: "Albert heeft veertig jaar ervaring in livecommunicatie. Hij bouwde een evenementen-, communicatie- en reclamebureau en een van Nederlands grootste evenementenlocaties op. Hij realiseerde projecten in binnen- en buitenland, was managing director van Light Art Collection en als bestuurder betrokken bij het Amsterdam Light Festival. Tegenwoordig leidt hij ELT Live, een bureau dat strategie en ambities vertaalt naar onderscheidende livecommunicatie in al haar vormen." },
  en: { title: "External adviser and sounding board", intro: "Drawing on that experience, Albert contributes ideas on the development, direction, growth and strategic choices of SocialNow.", experience: "Albert has forty years of experience in live communication. He built an events, communication and advertising agency and one of the largest event venues in the Netherlands. He delivered projects in the Netherlands and abroad, was managing director of Light Art Collection and served on the board of Amsterdam Light Festival. Today he leads ELT Live, an agency that translates strategy and ambitions into distinctive live communication in all its forms." },
  de: { title: "Externer Berater und Sparringspartner", intro: "Aus dieser Erfahrung heraus denkt Albert bei der Entwicklung, Ausrichtung, dem Wachstum und den strategischen Entscheidungen von SocialNow mit.", experience: "Albert verfügt über vierzig Jahre Erfahrung in der Live-Kommunikation. Er baute eine Veranstaltungs-, Kommunikations- und Werbeagentur sowie einen der größten Veranstaltungsorte der Niederlande auf. Er realisierte Projekte im In- und Ausland, war Managing Director von Light Art Collection und als Vorstandsmitglied beim Amsterdam Light Festival tätig. Heute leitet er ELT Live, eine Agentur, die Strategie und Ambitionen in unverwechselbare Live-Kommunikation in all ihren Formen übersetzt." },
  fr: { title: "Conseiller externe et interlocuteur de confiance", intro: "Fort de cette expérience, Albert contribue à la réflexion sur le développement, les orientations, la croissance et les choix stratégiques de SocialNow.", experience: "Albert possède quarante ans d’expérience en communication événementielle. Il a développé une agence d’événementiel, de communication et de publicité, ainsi que l’un des plus grands lieux événementiels des Pays-Bas. Il a réalisé des projets aux Pays-Bas et à l’étranger, a été managing director de Light Art Collection et a siégé au conseil d’administration de l’Amsterdam Light Festival. Il dirige aujourd’hui ELT Live, une agence qui traduit les stratégies et les ambitions en une communication événementielle distinctive sous toutes ses formes." },
  es: { title: "Asesor externo e interlocutor de confianza", intro: "Desde esa experiencia, Albert aporta ideas sobre el desarrollo, el rumbo, el crecimiento y las decisiones estratégicas de SocialNow.", experience: "Albert tiene cuarenta años de experiencia en comunicación en vivo. Creó una agencia de eventos, comunicación y publicidad y uno de los mayores espacios para eventos de los Países Bajos. Realizó proyectos nacionales e internacionales, fue managing director de Light Art Collection y miembro de la junta directiva del Amsterdam Light Festival. Actualmente dirige ELT Live, una agencia que traduce estrategias y ambiciones en una comunicación en vivo distintiva en todas sus formas." },
  it: { title: "Consulente esterno e interlocutore di fiducia", intro: "Forte di questa esperienza, Albert contribuisce allo sviluppo, alla direzione, alla crescita e alle scelte strategiche di SocialNow.", experience: "Albert ha quarant’anni di esperienza nella comunicazione dal vivo. Ha fondato e sviluppato un’agenzia di eventi, comunicazione e pubblicità e una delle più grandi sedi per eventi dei Paesi Bassi. Ha realizzato progetti nei Paesi Bassi e all’estero, è stato managing director di Light Art Collection e membro del consiglio di amministrazione dell’Amsterdam Light Festival. Oggi guida ELT Live, un’agenzia che traduce strategie e ambizioni in una comunicazione dal vivo distintiva in tutte le sue forme." },
  pt: { title: "Consultor externo e interlocutor de confiança", intro: "Com base nessa experiência, Albert contribui com ideias sobre o desenvolvimento, a direção, o crescimento e as escolhas estratégicas da SocialNow.", experience: "Albert tem quarenta anos de experiência em comunicação ao vivo. Criou e desenvolveu uma agência de eventos, comunicação e publicidade e um dos maiores espaços para eventos dos Países Baixos. Realizou projetos nacionais e internacionais, foi managing director da Light Art Collection e membro do conselho de administração do Amsterdam Light Festival. Atualmente dirige a ELT Live, uma agência que traduz estratégias e ambições em comunicação ao vivo diferenciada em todas as suas formas." },
  pl: { title: "Doradca zewnętrzny i partner do rozmów", intro: "Korzystając z tego doświadczenia, Albert wspiera refleksję nad rozwojem, kierunkiem, wzrostem i wyborami strategicznymi SocialNow.", experience: "Albert ma czterdzieści lat doświadczenia w komunikacji na żywo. Zbudował agencję eventową, komunikacyjną i reklamową oraz jeden z największych obiektów eventowych w Holandii. Realizował projekty w kraju i za granicą, był managing directorem Light Art Collection i członkiem zarządu Amsterdam Light Festival. Obecnie kieruje ELT Live, agencją przekładającą strategie i ambicje na wyróżniającą się komunikację na żywo we wszystkich jej formach." },
  sv: { title: "Extern rådgivare och bollplank", intro: "Utifrån den erfarenheten bidrar Albert med tankar om SocialNows utveckling, inriktning, tillväxt och strategiska val.", experience: "Albert har fyrtio års erfarenhet av livekommunikation. Han byggde upp en event-, kommunikations- och reklambyrå och en av Nederländernas största eventlokaler. Han genomförde projekt i Nederländerna och utomlands, var managing director för Light Art Collection och styrelseledamot i Amsterdam Light Festival. I dag leder han ELT Live, en byrå som omsätter strategier och ambitioner i särpräglad livekommunikation i alla dess former." },
  da: { title: "Ekstern rådgiver og sparringspartner", intro: "Med den erfaring bidrager Albert med tanker om SocialNows udvikling, retning, vækst og strategiske valg.", experience: "Albert har fyrre års erfaring med livekommunikation. Han opbyggede et event-, kommunikations- og reklamebureau og et af Nederlandenes største eventsteder. Han realiserede projekter i ind- og udland, var managing director for Light Art Collection og bestyrelsesmedlem i Amsterdam Light Festival. I dag leder han ELT Live, et bureau, der omsætter strategier og ambitioner til særpræget livekommunikation i alle dens former." },
};

export default function AdvisoryPartner() {
  const { language } = useLanguage();
  const text = copy[language] ?? copy.en;
  const albert = people.find(person => person.name === "Albert Deltour");
  if (!albert) return null;
  return <article className="sn-advisory" aria-label={`Albert Deltour · ${text.title}`} translate="no">
    <img className="sn-advisory-photo" {...klein(albert.image, "(max-width: 640px) 40vw, 200px", [160, 320])} alt="Albert Deltour" width="200" height="200" loading="lazy" />
    <div className="sn-advisory-copy">
      <small translate="no">Strategy &amp; Guidance Advisor — from ELT Live</small>
      <h3><a href={albert.linkedin} target="_blank" rel="noopener noreferrer">Albert Deltour <LinkedInMark /></a></h3>
      <strong>{text.title}</strong>
      <p>{text.experience}</p>
      <p>{text.intro}</p>
      <a className="sn-advisory-logo" href="https://www.eltlive.com/" target="_blank" rel="noopener noreferrer" aria-label="ELT Live">
        <img src="/images/merken/elt-live.webp" alt="ELT Live · Strategic Live Communication" width="1000" height="250" loading="lazy" decoding="async" />
      </a>
    </div>
  </article>;
}
