// 16 september 2026: de algemene voorwaarden en het privacybeleid als tekst, in twee talen.
// Eén bron voor de website (socialnow.nl/voorwaarden en /privacy) en de verwijzing vanuit
// het OS (app.socialnow.nl). De Nederlandse tekst is de bindende versie.
//
// Inhoud: de voorwaarden van de pdf van SocialNow (16 artikelen plus hosting, web en design)
// aangevuld met artikel 17 over SocialNow OS: het account, de gegevens die daarbij horen en het
// interne gebruik daarvan om het product te verbeteren.

export type Language = "en" | "nl" | "de" | "fr" | "it" | "es";
export type Section = { title: string; paragraphs: string[]; bullets?: string[][] };
export type LegalDoc = { title: string; intro: string; updated: string; sections: Section[] };

export const LEGAL_VERSION = "2026-09-17";

import { privacyNl, privacyEn } from "./legal-privacy";
import * as vertaald from "./legal-vertaald";

export const terms: Partial<Record<Language, LegalDoc>> & { nl: LegalDoc; en: LegalDoc } = {
  ...vertaald.terms,
  nl: {
    title: "Algemene voorwaarden",
    intro: "Deze voorwaarden gelden voor elke offerte, overeenkomst en elk gebruik van SocialNow OS. Bij aanmelding voor het OS ga je hiermee akkoord.",
    updated: "Laatst bijgewerkt: 16 september 2026",
    sections: [
      { title: "1. Definities", paragraphs: ["Opdrachtnemer: SocialNow, Amstelstraat 43G, 1017 DA Amsterdam, KVK 90877179. Opdrachtgever: de tegenpartij van opdrachtnemer, waaronder iedereen die een account aanmaakt in SocialNow OS. Overeenkomst: de overeenkomst tot dienstverlening, inclusief het gebruik van SocialNow OS."] },
      { title: "2. Algemeen", paragraphs: ["Deze voorwaarden gelden voor iedere offerte en overeenkomst tussen opdrachtnemer en een opdrachtgever. Afwijken kan alleen als partijen dat uitdrukkelijk schriftelijk vastleggen. Is een bepaling nietig of wordt die vernietigd, dan blijven de overige bepalingen van kracht en overleggen partijen over een vervangende bepaling die de strekking van de oorspronkelijke zo dicht mogelijk benadert."] },
      { title: "3. Uitvoering van de overeenkomst", paragraphs: ["Opdrachtnemer voert de overeenkomst naar beste inzicht en vermogen uit en mag werkzaamheden door derden laten verrichten. Opdrachtgever verstrekt tijdig alle gegevens die nodig zijn voor de uitvoering. Blijven die uit, dan mag opdrachtnemer de uitvoering opschorten en de extra kosten volgens de gebruikelijke tarieven in rekening brengen. Opdrachtnemer is niet aansprakelijk voor schade doordat is uitgegaan van onjuiste of onvolledige gegevens van opdrachtgever. Bij uitvoering in fasen mag opdrachtnemer een volgende fase opschorten tot opdrachtgever de vorige schriftelijk heeft goedgekeurd. Opdrachtgever vrijwaart opdrachtnemer voor aanspraken van derden die verband houden met de uitvoering en aan opdrachtgever toerekenbaar zijn."] },
      { title: "4. Wijziging van de overeenkomst", paragraphs: ["Blijkt tijdens de uitvoering dat de werkzaamheden gewijzigd of aangevuld moeten worden, dan passen partijen de overeenkomst tijdig en in overleg aan. Heeft dat financiële of kwalitatieve gevolgen, dan licht opdrachtnemer opdrachtgever daarover in, inclusief de gevolgen voor een vaste of periodieke prijs. Meerkosten die het gevolg zijn van omstandigheden die aan opdrachtnemer toe te rekenen zijn, worden niet in rekening gebracht."] },
      { title: "5. Contractduur", paragraphs: ["De overeenkomst wordt aangegaan voor onbepaalde tijd, tenzij anders overeengekomen. Een termijn voor de voltooiing van werkzaamheden is geen fatale termijn."] },
      { title: "6. Prijzen", paragraphs: ["Alle prijzen zijn exclusief btw en andere heffingen en exclusief kosten die in het kader van de overeenkomst worden gemaakt, tenzij anders vermeld. Zonder vaste of periodieke prijs geldt het gebruikelijke uurtarief van opdrachtnemer over de werkelijk bestede uren. Opdrachtnemer mag prijzen en tarieven verhogen en licht opdrachtgever daar tijdig over in, ook als inkooptarieven stijgen tussen aanbieding en levering of als de hoeveelheid werk buiten de schuld van opdrachtnemer te laag is ingeschat."] },
      { title: "7. Facturering en betaling", paragraphs: ["Bij akkoord op een offerte geldt een aanbetaling van 50% van de totaalprijs, te voldoen binnen de betalingstermijn op de factuur. Het restant wordt betaald binnen 14 dagen na factuurdatum. Bezwaren tegen de hoogte van een factuur schorten de betalingsverplichting niet op. Blijft betaling uit, dan volgt een herinnering per e-mail met een termijn van 7 dagen; daarna is opdrachtgever van rechtswege in verzuim en volgt een aanmaning met een termijn van 7 dagen en € 49,95 administratiekosten exclusief btw. Daarna mag opdrachtnemer de vordering overdragen aan een incassobureau; alle redelijke buitengerechtelijke en gerechtelijke kosten en rente komen voor rekening van opdrachtgever. Diensten die vooraf of periodiek betaald worden, worden pas geleverd na ontvangst van de betaling; bij uitblijvende betaling mag opdrachtnemer diensten tijdelijk of permanent afsluiten. Opdrachtgever gaat akkoord met facturering per e-mail, controleert zelf zijn inbox en spammap en meldt een gewijzigd e-mailadres tijdig."] },
      { title: "8. Revisies en garantie", paragraphs: ["Is het recht op revisies overeengekomen, dan kan opdrachtnemer per geval extra revisies toestaan als de opmerkingen van opdrachtgever redelijk zijn. Beide partijen kunnen de overeenkomst schriftelijk of per e-mail opzeggen. Zegt opdrachtgever tussentijds op, dan betaalt hij het bedrag uit de aanvullende voorwaarden en anders de declaraties voor het tot dan verrichte werk. Zegt opdrachtnemer op, dan draagt hij in overleg zorg voor overdracht van het resterende werk, tenzij de opzegging aan opdrachtgever toerekenbaar is; extra kosten van overdracht zijn voor opdrachtgever."] },
      { title: "9. Annulering en ontbinding", paragraphs: ["Opdrachtgever ziet af van het herroepingsrecht en de bedenktijd van 14 dagen bij koop op afstand: na ondertekening of akkoord via internet is de opdracht per direct definitief. Bij tussentijdse opzegging door opdrachtgever is de aanbetaling verschuldigd, plus de declaraties voor het verrichte werk en € 39,- annuleringskosten exclusief btw."] },
      { title: "10. Opschorting en ontbinding", paragraphs: ["Opdrachtnemer mag de nakoming opschorten of de overeenkomst ontbinden als opdrachtgever zijn verplichtingen niet of onvolledig nakomt, als er goede grond is te vrezen dat hij dat niet zal doen, als de diensten worden misbruikt of voor illegale doeleinden ingezet, als opdrachtgever schade aanbrengt aan derden, als gevraagde zekerheid uitblijft, of om een andere gegronde reden. Bij ontbinding zijn de vorderingen van opdrachtnemer direct opeisbaar. Opdrachtnemer behoudt steeds het recht op schadevergoeding."] },
      { title: "11. Aansprakelijkheid", paragraphs: ["Opdrachtnemer is niet aansprakelijk voor directe of indirecte schade door het gebruik van zijn diensten of producten. Is opdrachtnemer toch aansprakelijk voor directe schade, dan is die beperkt tot maximaal eenmaal de totaalprijs van het deel van de opdracht waarop de aansprakelijkheid betrekking heeft, en bij een looptijd langer dan drie maanden tot het bedrag over de laatste drie maanden. Onder directe schade vallen uitsluitend de redelijke kosten om oorzaak en omvang vast te stellen, om de gebrekkige prestatie alsnog aan de overeenkomst te laten beantwoorden en om schade te voorkomen of te beperken. Opdrachtnemer is nooit aansprakelijk voor gevolgschade, gederfde winst, gemiste besparingen of bedrijfsstagnatie."] },
      { title: "12. Vrijwaringen", paragraphs: ["Opdrachtgever vrijwaart opdrachtnemer voor aanspraken van derden over intellectuele eigendom op materialen of gegevens die opdrachtgever aanlevert. Aangeleverde bestanden en software zijn vrij van virussen en defecten."] },
      { title: "13. Overmacht", paragraphs: ["Partijen zijn niet gehouden tot nakoming als zij daartoe worden gehinderd door een omstandigheid die niet aan hun schuld te wijten is en niet voor hun rekening komt, waaronder alle van buiten komende oorzaken waarop opdrachtnemer geen invloed heeft. Tijdens overmacht worden verplichtingen opgeschort; duurt die langer dan twee maanden, dan mag ieder de overeenkomst ontbinden zonder schadevergoeding. Al nagekomen delen met zelfstandige waarde mogen apart worden gedeclareerd."] },
      { title: "14. Geheimhouding", paragraphs: ["Partijen houden informatie geheim die logischerwijs vertrouwelijk is of als vertrouwelijk is aangemerkt. Moet opdrachtnemer vertrouwelijke informatie verstrekken op grond van een rechterlijke uitspraak of wettelijke bepaling, dan is hij niet tot schadevergoeding gehouden."] },
      { title: "15. Auteursrecht en intellectueel eigendom", paragraphs: ["Opdrachtnemer behoudt de rechten die hem op grond van de Auteurswet toekomen. Verstrekte stukken, ontwerpen, software en andere resultaten zijn uitsluitend bestemd voor gebruik door opdrachtgever en mogen zonder toestemming niet worden verveelvoudigd, openbaar gemaakt of aan derden verstrekt. Opdrachtnemer mag de kennis die hij door de werkzaamheden opdoet voor andere doeleinden gebruiken, zolang geen vertrouwelijke informatie bij derden terechtkomt. Opdrachtgever stemt ermee in dat zijn logo, de gemaakte ontwerpen en zijn ervaringen herkenbaar voor promotie worden gebruikt, tenzij die gevoelige of vertrouwelijke informatie bevatten; opdrachtgever kan daar bezwaar tegen maken, waarna opdrachtnemer de publicatie niet plaatst of waar mogelijk verwijdert."] },
      { title: "16. Geschillen en toepasselijk recht", paragraphs: ["Partijen spannen zich in om een geschil in onderling overleg op te lossen. De rechter in de vestigingsplaats van opdrachtnemer is bij uitsluiting bevoegd, tenzij de kantonrechter bevoegd is. Op deze voorwaarden en elke overeenkomst is Nederlands recht van toepassing. Opdrachtnemer mag deze voorwaarden wijzigen en brengt opdrachtgever daarvan op de hoogte; de actuele versie staat altijd op socialnow.nl/voorwaarden."] },
      {
        title: "17. SocialNow OS: account, gegevens en verbetering",
        paragraphs: [
          "SocialNow OS is de online omgeving op app.socialnow.nl waarin opdrachtgever zijn website, klanten, content en advertenties beheert. Wie een account aanmaakt gaat akkoord met deze voorwaarden en met het privacybeleid op socialnow.nl/privacy.",
          "Opdrachtgever gaat ermee akkoord dat SocialNow de gegevens die bij zijn account en werkruimte horen intern mag inzien en analyseren. Dit gebeurt uitsluitend door het team van SocialNow, onder geheimhouding, en met één doel: de producten en diensten van SocialNow verbeteren. Denk aan het opsporen en verhelpen van fouten, het bepalen van wat er gebouwd wordt en het beter afstemmen van de SocialNow-modellen op wat klanten nodig hebben.",
          "SocialNow verkoopt deze gegevens nooit, deelt ze nooit met andere klanten en gebruikt ze nooit voor advertenties van derden. Gegevens van gekoppelde bronnen zoals Odoo, Meta en Google worden alleen gelezen voor de eigen werkruimte van opdrachtgever; de sleutels die opdrachtgever invoert worden versleuteld bewaard en niet getoond.",
          "Opdrachtgever blijft eigenaar van zijn gegevens en kan zijn account op elk moment verwijderen onder Account in het OS. Daarmee stopt het interne gebruik; SocialNow bewaart daarna alleen wat de wet vereist, zoals facturen.",
          "Het OS wordt geleverd zoals het is en wordt voortdurend doorontwikkeld. SocialNow geeft geen garantie op ononderbroken beschikbaarheid en mag functies wijzigen of beëindigen. Opdrachtgever gebruikt het OS niet voor illegale doeleinden, spam of misbruik van gekoppelde platformen en houdt zich aan de voorwaarden van die platformen.",
        ],
      },
      { title: "Aanvullend: hosting", paragraphs: ["Opdrachtnemer geeft voor hosting en systemen geen garantie op minimumsnelheden, ononderbroken werking of bereikbaarheid; schade daardoor, inclusief gevolgschade, is niet verhaalbaar. Opdrachtnemer is niet aansprakelijk voor door opdrachtgever geplaatste inhoud; schade door misbruik wordt op opdrachtgever verhaald. Abonnementen worden per einde contract schriftelijk opgezegd, tussentijds opzeggen is niet mogelijk en er vindt geen restitutie plaats. Opdrachtnemer mag de dienst per direct beëindigen bij vermoeden van illegale activiteiten of uitblijvende betaling; de betalingsverplichting loopt door tot de eerstvolgende opzegmogelijkheid. Domeinnaamregistraties gelden voor een jaar en worden telkens met een jaar verlengd; overige diensten zoals e-mail- en webhosting gelden voor drie maanden met stilzwijgende verlenging. De opzegtermijn is één maand; de opzegging moet uiterlijk twee dagen voor de nieuwe periode binnen zijn."] },
      { title: "Aanvullend: web solutions", paragraphs: ["Bij het ontwerp van een website, app of gebruikersinterface heeft opdrachtgever recht op twee revisies van het initiële ontwerp. Na schriftelijke goedkeuring geldt één maand garantie op de werking van het product in de staat waarin het is opgeleverd. Wijzigingen door anderen dan opdrachtnemer laten de garantie vervallen. Bij tussentijdse annulering is de aanbetaling verschuldigd, plus de declaraties voor het verrichte werk en € 39,- annuleringskosten exclusief btw; voorlopige resultaten worden waar redelijkerwijs mogelijk ter beschikking gesteld."] },
      { title: "Aanvullend: design en beeld", paragraphs: ["Bij een ontwerp heeft opdrachtgever recht op twee revisies van het initiële ontwerp. Voor gegevens die opdrachtgever aanlevert en in een ontwerp worden gebruikt is opdrachtnemer niet aansprakelijk voor (typ)fouten; de controle ligt bij opdrachtgever en het recht op garantie vervalt. Bij ontwerp inclusief druk geldt garantie op de kwaliteit van het drukwerk, waarbij de bewijsexemplaren van de drukker bindend zijn; lichte afwijkingen in kleur en kwaliteit kunnen voorkomen en de inschatting van opdrachtnemer daarover is bindend. Bij tussentijdse annulering gelden dezelfde kosten als bij web solutions."] },
    ],
  },
  en: {
    title: "Terms of Service",
    intro: "These terms apply to every quote, agreement and every use of SocialNow OS. By creating an account in the OS you agree to them. The Dutch version is the binding one.",
    updated: "Last updated: 16 September 2026",
    sections: [
      { title: "1. Definitions", paragraphs: ["Contractor: SocialNow, Amstelstraat 43G, 1017 DA Amsterdam, the Netherlands, Chamber of Commerce 90877179. Client: the counterparty of the contractor, including anyone who creates an account in SocialNow OS. Agreement: the agreement for services, including the use of SocialNow OS."] },
      { title: "2. General", paragraphs: ["These terms apply to every quote and agreement between the contractor and a client. Deviations are only valid when both parties record them explicitly in writing. If a provision is void or annulled, the other provisions remain in force and the parties agree on a replacement that stays as close as possible to the original intent."] },
      { title: "3. Performance", paragraphs: ["The contractor performs the agreement to the best of its knowledge and ability and may have work carried out by third parties. The client provides all information needed for performance in time. If it is not provided, the contractor may suspend the work and charge the extra costs at its usual rates. The contractor is not liable for damage caused by relying on incorrect or incomplete information from the client. When work is delivered in phases, the contractor may postpone a next phase until the client has approved the previous one in writing. The client indemnifies the contractor against third-party claims related to the performance that are attributable to the client."] },
      { title: "4. Changes", paragraphs: ["If it turns out during performance that the work has to be changed or extended, the parties adjust the agreement in time and in consultation. If that has financial or qualitative consequences, the contractor informs the client, including the effect on a fixed or periodic price. Extra costs caused by circumstances attributable to the contractor are not charged."] },
      { title: "5. Duration", paragraphs: ["The agreement is entered into for an indefinite period unless agreed otherwise. A deadline for completing work is not a strict deadline."] },
      { title: "6. Prices", paragraphs: ["All prices exclude VAT and other levies and exclude costs made in the context of the agreement, unless stated otherwise. Without a fixed or periodic price the contractor's usual hourly rate applies to the hours actually spent. The contractor may raise prices and rates and informs the client in time, also when purchase rates rise between quote and delivery or when the amount of work was underestimated through no fault of the contractor."] },
      { title: "7. Invoicing and payment", paragraphs: ["On acceptance of a quote a down payment of 50% of the total is due within the payment term on the invoice. The remainder is paid within 14 days of the invoice date. Objections to the amount of an invoice do not suspend the obligation to pay. If payment is not received, a reminder follows by e-mail with a 7-day term; after that the client is in default by operation of law and a demand follows with a 7-day term and € 49.95 administration costs excluding VAT. After that the contractor may hand the claim to a collection agency; all reasonable extrajudicial and judicial costs and interest are for the client. Services paid in advance or periodically are delivered only after payment is received; if payment stays out, the contractor may suspend or end services. The client agrees to invoicing by e-mail, checks their own inbox and spam folder, and reports a changed e-mail address in time."] },
      { title: "8. Revisions and warranty", paragraphs: ["Where a right to revisions is agreed, the contractor may allow extra revisions case by case when the client's remarks are reasonable. Both parties may terminate the agreement in writing or by e-mail. If the client terminates early, the amount from the additional terms is due, or otherwise the invoices for the work done so far. If the contractor terminates, it arranges the handover of remaining work in consultation, unless the termination is attributable to the client; extra handover costs are for the client."] },
      { title: "9. Cancellation", paragraphs: ["The client waives the right of withdrawal and the 14-day cooling-off period for distance purchases: once signed or accepted online, the order is final immediately. If the client terminates early, the down payment is due, plus the invoices for the work done and € 39 cancellation costs excluding VAT."] },
      { title: "10. Suspension and dissolution", paragraphs: ["The contractor may suspend performance or dissolve the agreement if the client does not fulfil its obligations or only partly, if there is good reason to fear it will not, if the services are abused or used for illegal purposes, if the client causes damage to third parties, if requested security is not provided, or for another well-founded reason. On dissolution the contractor's claims become immediately due. The contractor always keeps the right to claim damages."] },
      { title: "11. Liability", paragraphs: ["The contractor is not liable for direct or indirect damage from the use of its services or products. If the contractor is liable for direct damage after all, that liability is limited to at most once the total price of the part of the order it concerns, and for orders longer than three months to the amount due over the last three months. Direct damage only covers the reasonable costs of establishing cause and extent, of making the deficient performance meet the agreement, and of preventing or limiting damage. The contractor is never liable for consequential damage, lost profit, missed savings or business interruption."] },
      { title: "12. Indemnities", paragraphs: ["The client indemnifies the contractor against third-party claims about intellectual property on materials or data supplied by the client. Supplied files and software are free of viruses and defects."] },
      { title: "13. Force majeure", paragraphs: ["Neither party is obliged to perform when prevented by a circumstance that is not its fault and not for its account, including all external causes beyond the contractor's control. Obligations are suspended during force majeure; if it lasts longer than two months, either party may dissolve the agreement without compensation. Parts already performed with independent value may be invoiced separately."] },
      { title: "14. Confidentiality", paragraphs: ["The parties keep confidential all information that is logically confidential or marked as such. If the contractor has to disclose confidential information under a court order or legal provision, it owes no compensation."] },
      { title: "15. Copyright and intellectual property", paragraphs: ["The contractor keeps the rights it holds under copyright law. Supplied documents, designs, software and other results are meant only for use by the client and may not be reproduced, published or passed to third parties without permission. The contractor may use the knowledge gained through the work for other purposes as long as no confidential information reaches third parties. The client agrees that its logo, the designs made and its experiences may be used recognisably for promotion, unless they contain sensitive or confidential information; the client may object, after which the contractor does not publish or removes where possible."] },
      { title: "16. Disputes and governing law", paragraphs: ["The parties do their utmost to settle a dispute in consultation. The court in the contractor's place of business has exclusive jurisdiction, unless the subdistrict court is competent. Dutch law applies to these terms and every agreement. The contractor may change these terms and informs the client; the current version is always at socialnow.nl/voorwaarden."] },
      {
        title: "17. SocialNow OS: account, data and improvement",
        paragraphs: [
          "SocialNow OS is the online environment at app.socialnow.nl in which the client manages its website, customers, content and advertising. Whoever creates an account agrees to these terms and to the privacy policy at socialnow.nl/privacy.",
          "The client agrees that SocialNow may view and analyse the data belonging to its account and workspace internally. This is done only by the SocialNow team, under confidentiality, and for one purpose: improving SocialNow's products and services. That means finding and fixing errors, deciding what to build, and tuning the SocialNow models to what customers need.",
          "SocialNow never sells this data, never shares it with other customers and never uses it for third-party advertising. Data from connected sources such as Odoo, Meta and Google is read only for the client's own workspace; the keys the client enters are stored encrypted and never shown.",
          "The client remains the owner of its data and can delete its account at any time under Account in the OS. That ends the internal use; afterwards SocialNow keeps only what the law requires, such as invoices.",
          "The OS is provided as is and is continuously developed. SocialNow gives no guarantee of uninterrupted availability and may change or end features. The client does not use the OS for illegal purposes, spam or abuse of connected platforms and complies with the terms of those platforms.",
        ],
      },
      { title: "Additional: hosting", paragraphs: ["For hosting and systems the contractor gives no guarantee of minimum speeds, uninterrupted operation or availability; damage from these causes, including consequential damage, cannot be recovered. The contractor is not liable for content placed by the client; damage from abuse is recovered from the client. Subscriptions are cancelled in writing at the end of the contract; early cancellation is not possible and there is no refund. The contractor may end the service immediately on suspicion of illegal activity or non-payment; the obligation to pay continues until the next cancellation date. Domain registrations run for one year and renew yearly; other services such as e-mail and web hosting run for three months with tacit renewal. The notice period is one month and notice must be received at least two days before the new period starts."] },
      { title: "Additional: web solutions", paragraphs: ["For the design of a website, app or user interface the client is entitled to two revisions of the initial design. After written approval a one-month warranty applies to the working of the product in the state in which it was delivered. Changes by anyone other than the contractor void the warranty. On early cancellation the down payment is due, plus the invoices for the work done and € 39 cancellation costs excluding VAT; interim results are made available where reasonably possible."] },
      { title: "Additional: design and imagery", paragraphs: ["For a design the client is entitled to two revisions of the initial design. For data supplied by the client and used in a design, the contractor is not liable for typing or other errors; checking lies with the client and the warranty lapses. For design including print, the print quality is guaranteed, with the printer's proofs being binding; slight deviations in colour and quality can occur and the contractor's assessment of them is binding. On early cancellation the same costs apply as for web solutions."] },
    ],
  },
};

export const privacy: Partial<Record<Language, LegalDoc>> & { nl: LegalDoc; en: LegalDoc } = {
  nl: privacyNl,
  en: privacyEn,
  ...vertaald.privacy,
};

// 19 september 2026: de juridische laag is uit één artikel in het privacybeleid uitgegroeid tot
// zes documenten. Ze staan hier bij elkaar zodat de hubpagina, de voettekst en het pdf-script
// dezelfde lijst lezen en er nooit een document tussenuit valt.
//
// Het pad is tegelijk de bestandsnaam van de pdf in public/documenten.
export type LegalDocument = {
  slug: string;
  path: string;
  doc: Partial<Record<Language, LegalDoc>> & { nl: LegalDoc; en: LegalDoc };
  /** Eén regel die zegt wanneer je dit document nodig hebt, per taal. */
  waarvoor: Partial<Record<Language, string>> & { nl: string; en: string };
};
